#! /bin/sh -e
#
# Vyatta PAM config cleanup

pkg=vyatta-password-renewal
pam_unix=/usr/share/pam-configs/unix
pam_unix_bak=/opt/vyatta/share/pam-configs/unix.debian

if [ "$1" = remove ]; then
    if [ -e ${pam_unix_bak} ]; then
        dpkg-divert --package ${pkg} --remove --rename \
        --divert ${pam_unix_bak} ${pam_unix}
    fi
    rm -f /usr/share/pam-configs/vyatta-password
    pam-auth-update --package --force
fi

#DEBHELPER#

exit 0
