#!/usr/bin/perl

# **** License ****
#
# Copyright (c) 2020 AT&T Intellectual Property.
#   All Rights Reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#
#
# **** End License ****

use strict;
use warnings;
use File::Slurp qw(read_file);
use JSON;

my $opwdFile = '/etc/vyatta/login/opasswd.vyatta.json';

chomp( my $userpwd = <STDIN> );
my ( $user, $pwd ) = split( ':', $userpwd, 2 );
exit 0 if ( !defined($user) || !defined($pwd) );

exit 0 unless ( -e $opwdFile );
my $opwds = decode_json( read_file($opwdFile) );
exit 0 unless defined($opwds);
if ( exists $opwds->{$user} ) {
    foreach my $opwd ( @{ $opwds->{$user}->{'old-passwords'} } ) {
        my $npwd = crypt( $pwd, $opwd );
        exit 1 if ( $npwd && $npwd eq $opwd );
    }
}
exit 0;
